version: '3.9'
services:
  nginx:
    image: nginx:1.21-alpine
    ports:
      - "5000:5000"
    volumes:
      - ./docker/development/nginx/conf.d:/etc/nginx/conf.d
      - ./htpasswd:/etc/nginx/auth/htpasswd
    depends_on:
      - registry

  registry:
    image: registry:2.7
    volumes:
      - registry:/var/lib/registry

volumes:
  registry:
