# -*- mode: ruby -*-
# vi: set ft=ruby :

# bullseye64 (debian 11)
VAGRANT_BOX = "debian/bullseye64"
VM_NAME = 'privateDockerRegistry'
VM_USER = 'andrey'

Vagrant.configure("2") do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = VAGRANT_BOX

  config.vm.define VM_NAME

  # Actual machine name
  config.vm.hostname = VM_NAME

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  config.vm.box_check_update = false

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false

    vb.name = VM_NAME

    # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end

  # Update system
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update && sudo apt-get upgrade -y
  SHELL
end
